#!/usr/bin/env bash
# Check if the "listen 80 default_server;" line is present and correctly configured in the default site configuration file
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
