#!/usr/bin/env bash
# This script is displaying "Best School" 10 times while loop interrruptions in 4the and 8th 
counter=1
while [ $counter -lt 11 ]; do
if [ $counter -eq 4 ]; then
        echo "bad luck"
elif [ $counter -eq 8 ]; then
echo "good luck"
else
echo "Best School"
fi
((counter++))
done
